# These are supported funding model platforms

github: [babbastara85, user2]  # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: patreon_username  # Replace with a single Patreon username
open_collective: collective_username  # Replace with a single Open Collective username
ko_fi: ko-fi_username  # Replace with a single Ko-fi username
tidelift: npm/package_name  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: project_name  # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: liberapay_username  # Replace with a single Liberapay username
issuehunt: issuehunt_username  # Replace with a single IssueHunt username
otechie: otechie_username  # Replace with a single Otechie username
lfx_crowdfunding: lfx_project_name  # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: polar_username  # Replace with a single Polar username
custom: ['link1', 'link2']  # Replace with up to 4 custom sponsorship URLs
